commtool_template_homepage:
    pattern:  /
    defaults: { _controller: CommtoolTemplateBundle:Default:index }
    
commtool_template_section_properties:
    path:  /section/properties/{type}
    defaults: 
        _controller: CommtoolTemplateBundle:Section:properties
        type: null
