parameters:

services:
    template_section_factory:
        class: Optime\Commtool\TemplateBundle\SectionFactory
        arguments: ["@service_container", []]
    commtool_template_twig_extension:
        class: Optime\Commtool\TemplateBundle\Twig\Extension\TemplateExtension
        tags:
            - {name: twig.extension}
