parameters:

services:
    template_section_singleline:
        class: Optime\Commtool\TemplateBundle\Section\Singleline
        tags:
            - {name: commtool.section.type, alias: singleline}
    template_section_text:
        class: Optime\Commtool\TemplateBundle\Section\Text
        tags:
            - {name: commtool.section.type, alias: text}
    template_section_multiline:
        class: Optime\Commtool\TemplateBundle\Section\Multiline
        tags:
            - {name: commtool.section.type, alias: multiline}
    template_section_image:
        class: Optime\Commtool\TemplateBundle\Section\Image
        tags:
            - {name: commtool.section.type, alias: image}
    template_section_product:
        class: Optime\Commtool\TemplateBundle\Section\Product
        tags:
            - {name: commtool.section.type, alias: product}
    template_section_product_detail:
        class: Optime\Commtool\TemplateBundle\Section\ProductDetail
        tags:
            - {name: commtool.section.type, alias: product_detail}
    template_section_loop:
        class: Optime\Commtool\TemplateBundle\Section\Loop
        tags:
            - {name: commtool.section.type, alias: loop}